# Generated by Django 5.1.3 on 2024-11-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_identificationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationnumber',
            name='identification_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
